apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: writer2-jaeger
spec:
  strategy: production
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch:9200
  query:
    options:
      query:
        base-path: /jaeger